[project]
name = "textual-transit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtfs-realtime-bindings>=1.0.0",
    "protobuf>=6.30.2",
    "requests>=2.32.3",
    "textual>=3.1.1",
    "textual-dev>=1.7.0",
]
